    - name: 'Instala pacotes de dependencia do SO'
      apt:
        name: 
          - mysql-server
          - python3-mysqldb
        update_cache: yes
        state: latest
      become: yes

    - name: 'Cria o banco do MySQL' 
      mysql_db: 
        name: "{{ wp_db_name }}"
        login_user: root
        state: present
      become: yes

    - name: 'Cria usuário do MySQL'
      mysql_user:
        login_user: root
        name: "{{ wp_user_name }}"
        password: "{{ wp_user_password}}"
        priv: "{{ wp_db_name }}.*:ALL"
        state: present
        host: "{{ item }}"
      become: yes
      with_items:
        - "{{ wp_host_ip }}"
      notify:
        - restart mysql

    - name: 'Configura Mysql para aceitar conexões remotas'
      copy:
        src: 'files/mysqld.cnf'
        dest: '/etc/mysql/mysql.conf.d/mysqld.cnf'
      become: yes
      notify: 
        - restart mysql